### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Norach-I** [KafCoppelia/nonebot_plugin_fortune#3]
你好，我使用的是a16,尝试pip和nb安装0.1.2版本，报错提示只有0.2.0和0.2.1可以安装，然后就pip安装了0.2.1。bot.py文件中加入对应的加载插件语句nonebot.load_plugin("nonebot_plugin_fortune")后，python3运行bot.py文件。出现以下报错：
![image](https://user-images.githubusercontent.com/51918042/152682963-29993fc9-359a-41fb-a52b-7556e7b22c16.png)
请问该怎么解决这个报错才能运行。
资源文件已经下载解压放入对应路径下的resource/img文件夹中。
另外还想请教一下，readme文件中写的"env"文件，是bot.py文件同路径下的.env文件嘛？
![image](https://user-images.githubusercontent.com/51918042/152683058-75564336-4d9e-4274-93ff-277559219f3b.png)

**Comment by KafCoppelia** [comment]
v0.1.x适配a16，v0.2.0+适配b1，不要混用；指定版本安装用`nb plugin install`我不太清楚，但是用`pip install nonebot-plugin-fortune==0.1.2`可以安装；
报错是我的插件的bug，在最新的v0.3.2与v0.1.3已修复，v0.3.1与v0.1.2已撤销；
README中的`.env`具体取决于你所使用的环境配置文件，我的是将配置写在`.env.prod`文件内，参考nb2文档

**Comment by Norach-I** [comment]
感谢~我去重新下载安装试试。刚发现了我之前pip 0.1.2失败的原因了，默认在阿里云镜像没找到，换成了清华镜像可以了。thanks~
![image](https://user-images.githubusercontent.com/51918042/152686536-12e6d57b-fa65-4290-b17a-792b070f9d91.png)
