### ISSUE TITLE
AttributeError: 'FortuneManager' object has no attribute 'save'

### ISSUE THREAD

**Issue by YanHuanD** [KafCoppelia/nonebot_plugin_fortune#4]
你好，我使用的是beat.1，出现以下报错：
![image](https://user-images.githubusercontent.com/99136573/152691991-fc38133d-196d-48f6-b412-0533af3d83a1.png)

**Comment by KafCoppelia** [comment]
My bad，确实是bug，在最新版本0.3.3及dev分支已修复，其余含有此bug的版本已撤回。
