### ISSUE TITLE
同无报错，但运行时无返回，且直接导致服务器py占cpu100%而死机，其他函数全部被堵塞

### ISSUE THREAD

**Issue by 863109569** [KafCoppelia/nonebot_plugin_fortune#6]
![image](https://user-images.githubusercontent.com/77315378/153337605-ca6a6348-880a-4804-96b6-db4fc93922f0.png)

**Comment by KafCoppelia** [comment]
`过程试图写入的管道不存在`是ssh的问题吧？
我刚才重新用`v0.3.3`版本在b1下，使用repo中`resource`初始内容测试是OK的，确认一下你指定的`resource`路径是正确的

**Comment by 863109569** [comment]
![image](https://user-images.githubusercontent.com/77315378/153340303-96b9e730-0f9a-4bc8-81ba-b500e0ec0391.png)
![image](https://user-images.githubusercontent.com/77315378/153340316-f17b68d5-13c9-4462-846e-af2e08804dc4.png)
没指定resource，是默认的

**Comment by KafCoppelia** [comment]
泪目，如果插件没有报错我觉得很大程度上不是插件的😵

**Comment by KafCoppelia** [comment]
#7

**Comment by KafCoppelia** [comment]
若还有问题重新开启此issue
