### ISSUE TITLE
同无报错，无返回，服务器卡死，但是只在一个群有这种情况，其余群正常，有可能是什么原因呢

### ISSUE THREAD

**Issue by 19077frb** [KafCoppelia/nonebot_plugin_fortune#7]
![屏幕截图 2022-02-13 143435](https://user-images.githubusercontent.com/99540587/153741838-1c482139-b29b-43ef-a144-856bde0f433e.png)
只有最后一次的群失败，并且这个群每次都失败

**Comment by KafCoppelia** [comment]
看看cqhttp那边有无输出信息，看看是不是这个群bot被禁言了

**Comment by 19077frb** [comment]
![屏幕截图 2022-02-13 231437](https://user-images.githubusercontent.com/99540587/153759810-c787ea45-48c0-48b2-8e43-45ff521e4a28.png)
cqhttp有收到信息，但没有插件发送信息，没有被禁言

**Comment by KafCoppelia** [comment]
打开debug看一下输出；另外，确认一下抽签主题设置是否全为False，感觉可能进了死循环了；实在不行更新一下`0.3.4a1`

**Comment by 19077frb** [comment]
问题已解决，谢谢大佬

**Comment by KafCoppelia** [comment]
具体什么原因

**Comment by 19077frb** [comment]
> 

我没找到，我仅仅更新了最新版本，并把我之前的配置全部删除就成功了
这是我之前没更新时一次成功一次没成功的debug的记录
https://paste.ubuntu.com/p/sF8s6WFSJW/

**Comment by KafCoppelia** [comment]
好滴
