### ISSUE TITLE
插件无回应 识别不到指令

### ISSUE THREAD

**Issue by yuanzhidao** [KafCoppelia/nonebot_plugin_fortune#9]
02-19 15:29:06 [SUCCESS] nonebot | ONEBOT V11 2810708174 | [message.group.normal]: Message 62314204 from 208823829@[群:361400507] "今日运势"
02-19 15:29:06 [DEBUG] nonebot | Checking for matchers in priority 1...
02-19 15:29:06 [DEBUG] nonebot | Checking for matchers in priority 8...
02-19 15:29:06 [DEBUG] nonebot | Checking for matchers in priority 10...
02-19 15:29:06 [DEBUG] nonebot | Checking for matchers in priority 11...
02-19 15:29:06 [DEBUG] nonebot | Checking for matchers in priority 12...
02-19 15:29:06 [DEBUG] nonebot | Checking for matchers in priority 13...

正确安装了插件且下载了资源文件成功配置

**Comment by KafCoppelia** [comment]
是用的nb 2.0.0 beta2吗？目前插件使用在beta2上会加载失败

**Comment by yuanzhidao** [comment]
确实是b2 我去降个级 吧

**Comment by KafCoppelia** [comment]
v0.4.3支持b2辣
